# Artifact Hub repository metadata (see https://artifacthub.io/docs/topics/repositories/#verified-publisher)
repositoryID: 720d942c-5cb9-4af1-8f8b-965c76ff4834
owners:
  - name: Armagan Karatosun
    email: armagankaratosun@gmail.com
