{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "klustre-csi-plugin.fullname" . }}-node
  labels:
    {{- include "klustre-csi-plugin.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "klustre-csi-plugin.fullname" . }}-node
  labels:
    {{- include "klustre-csi-plugin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "klustre-csi-plugin.fullname" . }}-node
subjects:
  - kind: ServiceAccount
    name: {{ include "klustre-csi-plugin.serviceAccountName" . }}
    namespace: {{ include "klustre-csi-plugin.namespace" . | quote }}
{{- end }}
