{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name | quote }}
  labels:
    {{- include "klustre-csi-plugin.labels" . | nindent 4 }}
  {{- with .Values.storageClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ .Values.csiDriver.name | quote }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy | quote }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode | quote }}
{{- with .Values.storageClass.mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.storageClass.allowedTopologies }}
allowedTopologies:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
